assessment/urls.py
from django.conf.urls import url
from . import views

app_name = 'assessment'
urlpatterns = [
	url(r'^$', views.indexView, name = 'index'),
	url(r'^login$', views.loginView, name = 'login'),
	url(r'^logout$', views.logoutView, name = 'logout'),
	url(r'^vocab$', views.vocabView, name = 'vocab'),
	url(r'^vocab_query/(?P<vocab_word>[a-z ]+)/$', views.vocabQueryView, name = 'vocab_query'),
	url(r'^passage$', views.passageView, name = 'passage'),
]

language_site/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
	url(r'^admin/', include(admin.site.urls)),
	url(r'^assessment/', include('assessment.urls', namespace = "assessment")),
)

assessment/views.py
from django.shortcuts import render

from django.http import HttpResponseRedirect, HttpResponse
from django.template import loader
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from django.core.exceptions import ObjectDoesNotExist

from .models import *

import random, string, re

def indexView(request):
	context = {}
	if request.user.is_authenticated():
		context = get_index_context_from_user(request.user.username)
	else:
		# have we come here from the login page?
		if 'login' in request.POST.keys():
			# if so, try to log in
			username = request.POST['login']
			password = request.POST['password']
			user = authenticate(username = username, password = password)

			# is this a real account?
			if user is not None:
				# if so, log them in
				login(request, user)
				if user.is_authenticated():
					context = get_index_context_from_user(request.user.username)
			else:
				# if not, try again
				context = {'greeting':  "Invalid login info.  Please try again.", 'content': "", 'link': "login"}
		else:
			# if not, redirect to login
			context = {'greeting':  "You are not logged in.  Please login.", 'content': "", 'link': "login"}

	return render(request, 'assessment/index.html', context)

def loginView(request):
	context = {}
	return render(request, 'assessment/login.html', context)

def logoutView(request):
	context = {}
	logout(request)
	return render(request, 'assessment/logout.html', context)

@login_required(login_url='/assessment/login')
def vocabQueryView(request, vocab_word):
	# for vocab lookups during the passage
	context = {}
	st = Student.objects.get(name = request.user.username)

	# reject users who are done with the assessment

	if st.get_next_question_set_and_saved_responses_and_hints() == "finished":
		context['word'] = ""
		context['translation'] = ""
		context['definition'] = "No definitions are available as you have completed the assessment."
		return render(request, 'assessment/vocab_query.html', context)

	# give them the definition of this vocab word and note the query in the student database

	if vocab_word in [x.word for x in VocabHint.objects.all()]:
		vh = VocabHint.objects.get(word = vocab_word)
		st.add_vocab_query(vh)
		st.save()
		context['word'] = vh.word
		context['translation'] = vh.translation
		context['definition'] = vh.definition
	else:
		context['word'] = "Unknown word:  " + vocab_word
		context['translation'] = ""
		context['definition'] = "I don't know this word.  I'm not sure how you got here."

	return render(request, 'assessment/vocab_query.html', context)

@login_required(login_url='/assessment/login')
def vocabView(request):
	# for vocab quiz questions
	context = {}
	st = Student.objects.get(name = request.user.username)
	vresults = st.get_vocab_results()

	# process previous answer, if it exists (and the quiz is not over)
	if "is_word" in request.POST.keys() and len(vresults) < 150:
		previous_response = (request.POST["is_word"] == "yes")
		previous_word = request.POST["word"]
		vq = VocabQuestion.objects.get(word = previous_word)
		st.add_vocab_result(vq, previous_response)
		st.save()

	vresults = st.get_vocab_results() # Must re-retrieve b/c of new entry

	# present a new question, or, if they're done, present none

	context['num_complete'] = len(vresults)
	context['finished'] = len(vresults) >= 150
	if context['finished']:
		st.assign_passage()
		st.save()
		return render(request, 'assessment/vocab.html', context)
	else:
		# select the next word

		# select all words not already used
		unused_vqs = [x for x in VocabQuestion.objects.all() if not x in [y[0] for y in vresults]]

		# kband		nonword length
		# 1-2		3-7
		# 3-4		5-8
		# 5		5-9

		# gather unused words of first 5 kbands
		k_bands = [[] for x in range(5)]
		for band in range(5):
			k_bands[band] = [x for x in unused_vqs if x.k_band == band + 1]

		# sort nonwords into kbands
		nonwords_1_2 = [x for x in unused_vqs if x.k_band == -1 and len(x.word) >= 3 and len(x.word) <= 7]
		nonwords_3_4 = [x for x in unused_vqs if x.k_band == -1 and len(x.word) >= 5 and len(x.word) <= 8]
		nonwords_5 = [x for x in unused_vqs if x.k_band == -1 and len(x.word) >= 5 and len(x.word) <= 9]

		# figure out what k_band we should be in
		if len(vresults) < 30:
			# band 1
			w_count = len([x for x in vresults if x[0].k_band == 1])
			nw_count = len(vresults) - w_count

			if w_count == 20:
				# if we have twenty words, pick a non-word
				vq = random.choice(nonwords_1_2)
			elif nw_count == 10:
				# if we have ten non-words, pick a word
				vq = random.choice(k_bands[0])
			else:
				# otherwise, flip a 2:1 coin for word vs. nonword
				if random.randint(0, 2) == 0:
					vq = random.choice(nonwords_1_2)
				else:
					vq = random.choice(k_bands[0])
		elif len(vresults) < 60:
			# band 2
			w_count = len([x for x in vresults if x[0].k_band == 2])
			nw_count = len(vresults) - w_count - 30

			if w_count == 20:
				# if we have twenty words, pick a non-word
				vq = random.choice(nonwords_1_2)
			elif nw_count == 10:
				# if we have ten non-words, pick a word
				vq = random.choice(k_bands[1])
			else:
				# otherwise, flip a 2:1 coin for word vs. nonword
				if random.randint(0, 2) == 0:
					vq = random.choice(nonwords_1_2)
				else:
					vq = random.choice(k_bands[1])
		elif len(vresults) < 90:
			# band 3
			w_count = len([x for x in vresults if x[0].k_band == 3])
			nw_count = len(vresults) - w_count - 60

			if w_count == 20:
				# if we have twenty words, pick a non-word
				vq = random.choice(nonwords_3_4)
			elif nw_count == 10:
				# if we have ten non-words, pick a word
				vq = random.choice(k_bands[2])
			else:
				# otherwise, flip a 2:1 coin for word vs. nonword
				if random.randint(0, 2) == 0:
					vq = random.choice(nonwords_3_4)
				else:
					vq = random.choice(k_bands[2])
		elif len(vresults) < 120:
			# band 4
			w_count = len([x for x in vresults if x[0].k_band == 4])
			nw_count = len(vresults) - w_count - 90

			if w_count == 20:
				# if we have twenty words, pick a non-word
				vq = random.choice(nonwords_3_4)
			elif nw_count == 10:
				# if we have ten non-words, pick a word
				vq = random.choice(k_bands[3])
			else:
				# otherwise, flip a 2:1 coin for word vs. nonword
				if random.randint(0, 2) == 0:
					vq = random.choice(nonwords_3_4)
				else:
					vq = random.choice(k_bands[3])
		elif len(vresults) < 150:
			# band 5
			w_count = len([x for x in vresults if x[0].k_band == 5])
			nw_count = len(vresults) - w_count - 120

			if w_count == 20:
				# if we have twenty words, pick a non-word
				vq = random.choice(nonwords_5)
			elif nw_count == 10:
				# if we have ten non-words, pick a word
				vq = random.choice(k_bands[4])
			else:
				# otherwise, flip a 2:1 coin for word vs. nonword
				if random.randint(0, 2) == 0:
					vq = random.choice(nonwords_5)
				else:
					vq = random.choice(k_bands[4])

		context['word'] = vq.word
	return render(request, 'assessment/vocab.html', context)

@login_required(login_url='/assessment/login')
def passageView(request):
	context = {}
	st = Student.objects.get(name = request.user.username)
	# if vocab_score == -1, they shouldn't be here
	if st.vocab_score() == -1:
		context['message'] = "You need to go back to the index."
		return render(request, 'assessment/passage.html', context)
	context['message'] = "You get the " + st.passage_assigned + " passage."

	try:
		psg = Passage.objects.get(passage_name = st.passage_assigned)
	except ObjectDoesNotExist:
		context['message'] = "Error:  can't find assigned passage \'" + st.passage_assigned + "\'"
		return render(request, 'assessment/passage.html', context)

	context['passage_text'] = link_vocab_hints(psg.passage_text)

	# process previous answers, if any
	if not st.has_completed_passage():
		response_result = process_previous_passage_responses(request.POST, st)

	if response_result == "left_blanks":
		context['left_blanks'] = True

	# give a question set, if necessary
	next_qs_sr_h = st.get_next_question_set_and_saved_responses_and_hints()

	# if they've finished the passage, just return them
	if next_qs_sr_h == "finished":
		context['message'] = "Thank you for completing the assessment."
		context['passage_text'] = ""
		return render(request, 'assessment/passage.html', context)

	# Otherwise, give the next question set

	(qset, saved_rs, hints) = next_qs_sr_h
	pqs = PassageQuestion.objects.filter(question_set = qset, passage = st.passage_assigned)
	set_context_from_passage_questions(context, pqs, saved_rs, hints)
	return render(request, 'assessment/passage.html', context)

def process_previous_passage_responses(postdata, st):
	"Takes in POST data and Student, updates student passage results."
	question_index = 0
	qi_str = str(question_index)
	responses = []

	# if we have questions from the wrong question set, reject this data
	question_set = st.pq_set_queue_peek()[0]
	if "question_id0" in postdata.keys():
		try:
			pq = PassageQuestion.objects.get(pq_id = postdata["question_id0"])
		except ObjectDoesNotExist:
			# Rejecting:  invalid question data in referrer
			return "invalid_question"
		if pq.question_set != question_set:
			# Rejected because wrong question set present.
			# This probably happened b/c the user hit back and resubmit
			return "wrong_question_set"

	question_skipped = False
	while "question_id" + qi_str in postdata.keys():
		# We always append a response, even if it's blank.  This way, we always
		# pass the correct number of responses
		pq = PassageQuestion.objects.get(pq_id = postdata["question_id" + qi_str])

		if pq.question_type == "pick one":
			if "pickone" + qi_str in postdata.keys():
				response = postdata["pickone" + qi_str]
			else:
				response = "-1"  # if left blank
				question_skipped = True
		elif pq.question_type == "pick many":

assessment/templates/assessment/index.html
<h1>Welcome to the language assessment!</h1>
<p>{{ greeting }}</p>
{# Vocab quiz results #}
{% if scores %}
	<h3>Vocabulary Size Test Results</h3>
	<p>
	<table border="1">
	<tr>
	<td>K Band</td>
	<td>Score</td>
	</tr>
	{% for score in scores %}
		<tr>
		<td>{{ forloop.counter }}</td>
		<td>{{ score }}%</td>
		</tr>
	{% endfor %}
	</table><br />
	K-band scores estimate how many of the most frequent words you know in English.  For example, K-band 1 roughly estimates what percentage of the most 1000 frequent words that you know.<br /><br />
	Your overall vocabulary score was {{ overall_score }}%
	</p>
{% endif %}
<p>{{ content }}</p>
<p>
{% if link == "login" %}
	<a href = "{% url 'assessment:login' %}">Login page</a>
{% endif %}
{% if link == "vocab" %}
	<a href = "{% url 'assessment:vocab' %}">Take the vocab quiz</a>
{% endif %}
{% if link == "passage" %}
	<a href = "{% url 'assessment:passage' %}">Take the passage test</a>
{% endif %}
{% if link == "logout" %}
	<a href = "{% url 'assessment:logout' %}">Log out</a>
{% endif %}
{% if link != "login" and link != "logout" %}
<br />
<br />
Or, you may <a href = "{% url 'assessment:logout' %}">log out</a>.
{% endif %}
</p>

assessment/templates/assessment/login.html
<h1>Login</h1>
	<p>Please log in.</p><br />
	<form method="post" action="/assessment/">
	{% csrf_token %}
        <p><input type="text" name="login" value="" placeholder="Username"></p>
        <p><input type="password" name="password" value="" placeholder="Password"></p>
        </p>
        <p class="submit"><input type="submit" name="commit" value="Login"></p>
      </form>

assessment/templates/assessment/logout.html
<h1>Logout</h1>
<p>You have been logged out.</p><br />
<p>You may log in via the <a href = "{% url 'assessment:login' %}">login page</a>.</p>

assessment/templates/assessment/passage.html
<!DOCTYPE html>
<html>
<head>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'assessment/passage.css' %}" />
<script src="{% static 'assessment/passage.js' %}">
</script>
</head>
<body>
<h1>Passage quiz</h1>
<p>{{ message }}</p><br /><br />
{% if questions %}
	<table>
	<tr>
	<td width="50%">
	<p>{{ passage_text|safe }}</p>
	</td>
	<td>
	{# if they left questions blank last time #}
	{% if left_blanks %}
		<p style="color:blue">You must answer every question before submitting an answer.  If you would like to save your answers so far and come back to this question later, click "Skip and come back."</p>
	{% endif %}
	{# questions #}
	<form method="post" action="passage" id="answerform">
	{% csrf_token %}
	<p><b>({{ question_set }})</b></p>
	{% for question in questions %}
		<p>
		{% if question.type == "pick one" or question.type == "pick many" or question.type == "short response" or question.type == "long response" %}
			{{ question.prompt|safe }}
		{% endif %}
		</p>
		{# hint #}
		<p style="color:red">
		{% if question.hint %}
			{{ question.hint }}
		{% endif %}
		</p>
		{# user inputs #}
		<p>
		{% if question.type == "pick one" %}
			{% for answer_choice in question.answer_choices %}
				<p>
				{% if question.saved_response == forloop.counter0 %}
					<input type="radio" name="pickone{{ forloop.parentloop.counter0 }}" value="{{ forloop.counter0 }}" checked>{{ answer_choice }}
				{% else %}
					<input type="radio" name="pickone{{ forloop.parentloop.counter0 }}" value="{{ forloop.counter0 }}">{{ answer_choice }}
				{% endif %}
				</p>
			{% endfor %}
		{% endif %}
		{% if question.type == "pick many" %}
			{% for answer_choice in question.answer_choices %}
				<p>
				{% if forloop.counter0 in question.saved_response %}
					<input type="checkbox" name="pickmany{{ forloop.parentloop.counter0 }}-{{ forloop.counter0 }}" value="{{ forloop.counter0 }}" checked>{{ answer_choice }}
				{% else %}
					<input type="checkbox" name="pickmany{{ forloop.parentloop.counter0 }}-{{ forloop.counter0 }}" value="{{ forloop.counter0 }}">{{ answer_choice }}
				{% endif %}
				</p>
			{% endfor %}
		{% endif %}
		{% if question.type == "short response" %}
			<textarea name="shortresponse{{ forloop.counter0 }}" form="answerform">{{ question.saved_response }}</textarea>
		{% endif %}
		{% if question.type = "long response" %}
			<textarea name="longresponse{{ forloop.counter0 }}" form="answerform">{{ question.saved_response }}</textarea>
		{% endif %}
		<input type="hidden" name="question_id{{ forloop.counter0 }}" value="{{ question.id }}">
		</p>
	{% endfor %}
	<input type="submit" name="submit" value="Submit and go on">
	<input type="submit" name="submit" value="Skip and come back">
	</form>
	</td>
	</tr>
	</table>
{% endif %}
</body>
</html>

assessment/templates/assessment/vocab.html
<html>
<head>
<title>Language Assessment</title>
<script>
function yn_press(e)
{
	if(e.keyCode == 89)
	{
		document.forms[0].is_word.value = "yes";
		document.forms[0].submit()
	}
	if(e.keyCode == 78)
	{
		document.forms[0].is_word.value = "no";
		document.forms[0].submit()
	}
}
</script>
</head>
<body onkeydown="yn_press(event)">
<h1>Vocab quiz</h1>
<p>You have completed {{ num_complete }} question(s).</p>
{% if finished %}
	<p>You are done with vocab.  Please <a href = "{% url 'assessment:index' %}">click here</a> to continue your assessment.</p><br />
{% else %}
	<p>Is "{{ word }}" a word?</p><br />
	<div onKeyPress="return yn_press(event)">
	<form method="post" action="vocab">
	{% csrf_token %}
	<p><input type="hidden" name="word" value="{{ word }}"></p>
       	<p><input type="radio" accesskey="y" name="is_word" value="yes" checked>Yes</p>
       	<p><input type="radio" accesskey="n" name="is_word" value="no">No</p>
       	</p>
	<p>(You may also type "n" to answer "No" or type "y" to answer "Yes.")</p>
       	<p class="submit"><input type="submit" name="commit" value="Submit"></p>
     	</form>
	</div>
{% endif %}
</body>
</html>

assessment/templates/assessment/vocab_query.html
<h1>Vocab Lookup</h1>
{% if definition %}
	<p><b>{{ word }}</b></p><br /><br />
	<p>Spanish:  <i>{{ translation }}</i></p><br /><br />
	<p>English:  {{ definition }}</p><br /><br />
{% else %}
	<p>Couldn't look up {{ word }}.  Not sure how you got here.</p><br />
{% endif %}